menu:
    Blog: /
    Archive: /archives/
    Dribbble: http://dribbble.com/linxiaopeng
    GitHub: https://github.com/linxiaopeng
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2018
